tentacle/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^(?P<activity_id>[0-9]+)/$', views.detail, name='detail'),
        url(r'^(?P<activity_id>[0-9]+)/delete/$', views.delete_activity, name='delete'),
        ]

tentacle_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('tentacle.urls', namespace='tentacle_ns')),
]

tentacle/models.py
from django.db import models

class Activity(models.Model):
    activity_name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    latest_hour = models.IntegerField(default=0)
    total_hour = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    parent_activity = models.ForeignKey('self', default=0)

    def __str__(self):
        return self.activity_name

    def update_total_hour(self):
    	self.total_hour += self.latest_hour
    	return self.total_hour

class Note(models.Model):
    note = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=100)
    activity = models.ForeignKey(Activity)

tentacle/forms.py
from django import forms
from .models import Activity

class AddActivityForm(forms.Form):
    name = forms.CharField(max_length=20)
    description = forms.CharField(max_length=140)
    parent = forms.ModelChoiceField(queryset=Activity.objects.filter(parent_activity_id=0), initial={0:''})

class EditActivityForm(forms.Form):
    name = forms.CharField(max_length=20, label="Activity name")
    description = forms.CharField(max_length=140, label="Description")

class IncreaseHourForm(forms.Form):
    CHOICES = [('pos', 'Add'), ('neg', 'Sub')]
    choice_field = forms.ChoiceField(widget=forms.RadioSelect(), choices=CHOICES, initial='pos')
    num = forms.CharField(max_length=4)
    note = forms.CharField(max_length=140, required=False)

tentacle/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Activity, Note
from .forms import AddActivityForm, EditActivityForm, IncreaseHourForm
from django.utils import timezone

def index(request):
    activities = Activity.objects.order_by('-total_hour')
    activity_list = activities.filter(parent_activity_id = 0)
    top_level_activity = activity_list.exclude(id=0)
    return render(request, 'tentacle/index.html', {'top_level_activity': top_level_activity})

def detail(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    notes = Note.objects.filter(activity_id=activity_id)

    # Increase and decrease total hour form.
    if request.method == 'POST':
        if 'add_act_btn' in request.POST:
            add_activity_form = AddActivityForm(request.POST)
            if add_activity_form.is_valid():
                name = add_activity_form.cleaned_data['name']
                description = add_activity_form.cleaned_data['description']
                parent = add_activity_form.cleaned_data['parent']
                a = Activity(activity_name=name, description=description, parent_activity=parent)
                a.save()
                return HttpResponseRedirect('/')
        if 'edit_act_btn' in request.POST:
            edit_activity_form = EditActivityForm(request.POST)
            if edit_activity_form.is_valid():
                activity.activity_name = edit_activity_form.cleaned_data['name']
                activity.description = edit_activity_form.cleaned_data['description']
                activity.save()
                return HttpResponseRedirect('/' + activity_id)
        elif 'inc_hour_btn' in request.POST:
            increase_hour_form = IncreaseHourForm(request.POST)
            if increase_hour_form.is_valid():
                choice = increase_hour_form.cleaned_data['choice_field']
                if choice == 'pos':
                    num = int(increase_hour_form.cleaned_data['num'])
                    inc_status = "added"
                elif choice == 'neg':
                    num = -int(increase_hour_form.cleaned_data['num'])
                    inc_status = "sub"
                activity.latest_hour = num
                activity.update_total_hour()
                activity.save()
                note = increase_hour_form.cleaned_data['note']
                if note:
                    status = "%s %d hour to %s" % (inc_status, int(increase_hour_form.cleaned_data['num']), activity.activity_name)
                    n = Note(note=note, status=status ,activity_id=activity_id)
                    n.save()
                return HttpResponseRedirect('/' + activity_id)
    else:
        add_activity_form = AddActivityForm()
        edit_activity_form = EditActivityForm()
        increase_hour_form = IncreaseHourForm()


    activities = Activity.objects.order_by('-total_hour')
    activity_list = activities.filter(parent_activity_id = 0)
    top_level_activity = activity_list.exclude(id=0)

    return render(request, 'tentacle/detail.html', {'activity': activity, \
            'add_activity_form': add_activity_form, 'edit_activity_form': edit_activity_form,\
            'increase_hour_form': increase_hour_form, \
            'top_level_activity': top_level_activity, 'notes': notes})

def delete_activity(request, activity_id=None):
    activity = get_object_or_404(Activity, pk=activity_id)
    activity.delete()
    return HttpResponseRedirect('/')

tentacle/templates/tentacle/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Tentacle</title>
    <!-- Bootstrap -->
    <link href="{% static 'tentacle/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <!-- Custom CSS -->
    <link href="{% static 'tentacle/css/style.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'tentacle/css/style-responsive.css' %}" rel="stylesheet" media="screen">
    <!-- Font Awesome -->
    <link href="{% static 'tentacle/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" media="screen">
    <!-- Zabuto Calendar -->
    <link href="{% static 'tentacle/css/zabuto-calendar.css' %}" rel="stylesheet" media="screen">
    <!-- Lineicons -->
    <link rel="stylesheet" type="text/css" href="{% static 'tentacle/lineicons/style.css'%}">
    <!-- jQuery Gritter -->
    <link href="{% static 'tentacle/gritter/css/jquery.gritter.css' %}" rel="stylesheet" media="screen">

    <link href="{% static 'tentacle/VerticalTimeline/css/component.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'tentacle/css/sidebar-hierarchy.css' %}" rel="stylesheet" media="screen">
</head>

<body>

<section id="container" >
  <!-- **********************************************************************************************************************************************************
  TOP BAR CONTENT & NOTIFICATIONS
  *********************************************************************************************************************************************************** -->
  <!--header start-->
  <header class="header black-bg">
        <!--logo start-->
        <a href="/" class="logo"><b>TENTACLE pre-alpha</b></a>
        <!--logo end-->
        <div class="nav notify-row" id="top_menu">
            <!--  notification start -->
            <ul class="nav top-menu">
                <!-- settings start -->
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                        <i class="fa fa-tasks"></i>
                        <span class="badge bg-theme">4</span>
                    </a>
                </li>
                <!-- settings end -->
                <!-- inbox dropdown start-->
                <li id="header_inbox_bar" class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-theme">5</span>
                    </a>
                </li>
                <!-- inbox dropdown end -->
            </ul>
            <!--  notification end -->
        </div>
        <div class="top-menu">
            <ul class="nav pull-right top-menu">
                <li><a class="logout" href="login.html">Logout</a></li>
            </ul>
        </div>
    </header>
  <!--header end-->
  
  <!-- **********************************************************************************************************************************************************
  MAIN CONTENT
  *********************************************************************************************************************************************************** -->
  <!--main content start-->
  <section id="main-content">
      <section class="wrapper">

          <div class="row">
              <div class="col-lg-3 ds">
                <h3>Activities</h3>
                  <div class="clt">
                    <ul>
                        <!-- List of activities -->
                        {% if top_level_activity %}
                            {% for activity in top_level_activity %}
                          <li>
                              <a href="{% url 'tentacle_ns:detail' activity.id %}">{{ activity.activity_name }}</a>
                              <ul>
                                {% for activity_tier_2 in activity.activity_set.all %}
                                  <li>
                                    <a href="{% url 'tentacle_ns:detail' activity_tier_2.id %}">{{ activity_tier_2.activity_name }}</a>
                                    <ul>
                                      {% for activity_tier_3 in activity_tier_2.activity_set.all %}
                                      <li>
                                        <a href="{% url 'tentacle_ns:detail' activity_tier_3.id %}">{{ activity_tier_3.activity_name }}</a>
                                      </li>
                                      {% endfor %}
                                    </ul>
                                  </li>  
                                {% endfor %}
                              </ul>  
                            </li>
                            {% endfor %}
                        {% else %}
                            <li>No activities are avalilable.</li>
                        {% endif %}
                    </ul>
                  </div>
                
              </div>
              
              <div class="col-lg-6 main-chart">

                <div class="row-mt">
                  {% block add-hour %}
                  {% endblock %}
                </div>
                
                <div class="row mt">
                    <div style="margin-left:15px; margin-right:15px;">
                        {% block timeline %}
                        {% endblock %}
                    </div>
                </div><!-- /row --> 
                
              </div><!-- /col-lg-9 END SECTION MIDDLE -->
              
              
  <!-- **********************************************************************************************************************************************************
  RIGHT SIDEBAR CONTENT
  *********************************************************************************************************************************************************** -->                  
              
              <div class="col-lg-3 ds">
                    {% block content %}
                    {% endblock %}

                        
              </div><!-- /col-lg-3 -->
          </div><!--/row -->
      </section>
  </section>

  <!--main content end-->
  <!--footer start-->
  <footer class="site-footer">
      <div class="text-center">
          2015 - Tentacle
          <a href="#" class="go-top">
              <i class="fa fa-angle-up"></i>
          </a>
      </div>
  </footer>
  <!--footer end-->
</section>

<script src="{% static 'tentacle/js/jquery-2.1.4.min.js'%}"></script>
<script src="{% static 'tentacle/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- js placed at the end of the document so the pages load faster -->

<script class="include" src="{% static 'tentacle/js/jquery.dcjqaccordion.2.7.js' %}"></script>
<script src="{% static 'tentacle/js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'tentacle/js/jquery.nicescroll.js' %}"></script>
<script src="{% static 'tentacle/js/jquery.sparkline.js' %}"></script>


<!--common script for all pages-->
<script src="{% static 'tentacle/js/common-scripts.js' %}"></script>

<script src="{% static 'tentacle/gritter/js/jquery.gritter.js' %}"></script>
<script src="{% static 'tentacle/js/gritter-conf.js' %}"></script>

<!--script for this page-->
<script src="{% static 'tentacle/js/sparkline-chart.js' %}"></script>    
<script src="{% static 'tentacle/js/zabuto_calendar.js' %}"></script>    

<script src="{% static 'tentacle/VerticalTimeline/js/modernizr.custom.js' %}"></script>  

<script type="text/javascript">
  $('.tree-toggle').click(function () {
    $(this).parent().children('ul.tree').toggle(200);
  });
</script>
<script type="application/javascript">
    $(document).ready(function () {
        $("#date-popover").popover({html: true, trigger: "manual"});
        $("#date-popover").hide();
        $("#date-popover").click(function (e) {
            $(this).hide();
        });
    
        $("#my-calendar").zabuto_calendar({
            action: function () {
                return myDateFunction(this.id, false);
            },
            action_nav: function () {
                return myNavFunction(this.id);
            },
            ajax: {
                url: "show_data.php?action=1",
                modal: true
            },
            legend: [
                {type: "text", label: "Special event", badge: "00"},
                {type: "block", label: "Regular event", }
            ]
        });
    });
    
    
    function myNavFunction(id) {
        $("#date-popover").hide();
        var nav = $("#" + id).data("navigation");
        var to = $("#" + id).data("to");
        console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
    }
</script>


</body>

</html>

tentacle/templates/tentacle/detail.html
{% extends "tentacle/base.html" %}

{% block add-activity %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="">Activity name</label>
            <input type="text" class="form-control" name="{{ add_activity_form.name.name }}" placeholder="" >
        </div>
        <div class="form-group">
            <label for="">Description</label>
            <textarea rows="3" class="form-control" name="{{ add_activity_form.description.name }}" placeholder="Description"></textarea>
        </div>
        <div class="form-group">
            <label for="">Parent activity</label>
            <select class="form-control" name="parent">
                {% for choice in add_activity_form.parent.field.choices %}
                <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
            <p class="help-block">Each time you add hour .....</p>
        </div>
        <div class="form-group">
            <input type="submit" name="add_act_btn" value="Submit" class="btn btn-default" />
        </div>
    </form>
{% endblock%}


{% block content %}
<div class="col-md-12 mb">
    <div class="darkblue-panel pn">
        <div class="darkblue-header">
            <h4>{{ activity.activity_name }}</h4>
        </div>
        <p><em>"{{ activity.description}}"</em></p>
        <font size="20">{{ activity.total_hour }} <span>hours</span></font>
        <p>since {{ activity.created_at}}</p>
        <div class="chart mt">
            <div class="sparkline" data-type="line" data-resize="true" data-height="75" data-width="90%" data-line-width="1" data-line-color="#fff" data-spot-color="#fff" data-fill-color="" data-highlight-line-color="#fff" data-spot-radius="5" data-data="[0,4,3,3,2,3,2,6,4,1,2]"></div>
        </div>
        {% with inc_status="added" dec_status="sub"%}
        {% if activity.latest_hour > 0 %}
        <p class="mt">Recently, you {{ inc_status }} {{activity.latest_hour}} hours
        <br>in {{ activity.updated_at}}</p>
        {% else %}
        <p class="mt">Recently, you {{ inc_status }} {{activity.latest_hour}} hours
        <br>in {{ activity.updated_at}}</p>
        {% endif %}
        {% endwith %}
        <div class="percent">{% widthratio activity.total_hour 10000 100 %}%</div>
        <div class="progress progress-striped active">
            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="{{ activity.total_hour }}" aria-valuemin="0" aria-valuemax="10000" style="width: {% widthratio activity.total_hour 10000 100 %}%">
            <span>{{ activity.total_hour }} of 10000</span>
            </div>
        </div>
        <div>
            <p><i class="fa fa-sticky-note"></i>  {{ notes.count }} Note | <i class="fa fa-graduation-cap"></i> for badge</p>
        </div>
        <footer>
            <!-- Button trigger modal -->
            <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
              Edit Activity
            </button>
            
            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Activity detail</h4>
                  </div>
                  <div class="modal-body" style="color:#000">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="activityName">Activity name</label>
                            <input type="text" id="activityName" class="form-control" name="{{ edit_activity_form.name.name }}" placeholder="" value="{{ activity.activity_name }}">
                        </div>
                        <div class="form-group">
                            <label for="">Description</label>
                            <textarea rows="3" class="form-control" name="{{ edit_activity_form.description.name }}" placeholder="Description">{{ activity.description }}</textarea>
                        </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" name="edit_act_btn" value="Save changes" class="btn btn-primary" />
                  </div>
                  </form>
                </div>
              </div>
            </div>  
            <a href="{% url 'tentacle_ns:delete' activity_id=activity.id %}" class="btn btn-danger btn-sm" style="color:#fff">
            Delete Activity
            </a>     
       </footer>
    </div><!-- /darkblue panel -->
</div><!-- /col-md-4 -->
{% endblock %}

{% block add-hour %}
{% if increase_hour_form.errors %}
    {{ increase_hour_form.errors|pluralize }}
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <div class="form-inline">
            <div class="form-group">
                <div class="input-group">
                {% for choice in increase_hour_form.choice_field.field.choices %}
                  <span class="input-group-addon input-sm">
                    <input type="radio" name="choice_field" value="{{ choice.0 }}">
                  </span>
                  <input type="text" class="form-control input-sm" value="{{choice.1}}" readonly>
                {% endfor %}
                </div><!-- /input-group -->
                
                <div class="input-group">
                    <input type="text" class="form-control input-sm" name="{{ increase_hour_form.num.name }}" placeholder="Number of hours">
                    <div class="input-group-addon">hours</div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <textarea rows="3" class="form-control input-sm" name="{{ increase_hour_form.note.name }}" placeholder="Add note (optional)"></textarea>
    </div>
    <div class="form-group">
        <input type="submit" name="inc_hour_btn" value="Submit" class="btn btn-primary btn-sm" />
    </div>
</form>
{% endblock %}

{% block timeline %}
<ul class="cbp_tmtimeline">
{% for note in notes %}
    <li>
        <time class="cbp_tmtime" datetime="{{ note.created_at }}"><span>4/10/13</span> <span>18:30</span></time>
        <div class="cbp_tmicon cbp_tmicon-phone"></div>
        <div class="cbp_tmlabel">
            <h2>{{ note.status }}</h2>
            <p>{{ note.note }}</p>
        </div>
    </li>
{% endfor %}
</ul>
{% endblock%}

tentacle/templates/tentacle/index.html
                            <div class="list-group">
                                <ul class="nav"> 
                                <!-- List of activities -->
                                {% if top_level_activity %}
                                    {% for activity in top_level_activity %}
                                    <li>
                                      <a href="{% url 'tentacle_ns:detail' activity.id %}" class="list-group-item">{{ activity.activity_name }}</a>
                                      <ul class="nav nav-second-level">
                                        {% for child_activity in activity.activity_set.all %}
                                          <li>
                                            <a href="{% url 'tentacle_ns:detail' child_activity.id %}" class="list-group-item">{{ child_activity.activity_name }}</a>
                                          </li>  
                                        {% endfor %}
                                      </ul>  
                                    </li>
                                    {% endfor %}
                                {% else %}
                                    <li>No activities are avalilable.</li>
                                {% endif %}
                                </ul>
                            </div>